In [1]:
import numpy as np

#### Matriz initialization

In [3]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# check dimension
a.ndim

2

In [7]:
a.shape

(2, 4)

In [11]:
len(a) == a.shape[0]

True

In [12]:
a.shape[1]

4

In [13]:
# matrix, 3 rows and two columns
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.full((3, 2), 10)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [16]:
np.empty((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Random matrix generation

In [23]:
np.random.randint(0, 10, (3, 2)) # random integer and many others see the doc

array([[9, 7],
       [2, 4],
       [1, 1]])

#### 2d Indexing