# NumPy Basics
#### Objectives:
* Understand the difference between one-, two- and n-dimensional arrays in NumPy;
* Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;
* Understand axis and shape properties for n-dimensional arrays.


## Basics 
The main object in numpy is the homogeneous multidimensional array. It is like table of elements with the same type. One important thing in numpy is that dimensions are called axes. 
For example the array of `[1, 2, 1]` has one axis. The axis has three elements. The array below is a two dimensional array, meaning that it has two axes. The first axis has the length of two, the second axis has the element of three. 

In [1]:
[[1., 0., 0.],
 [0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

### ndarray
NumPy's array class is called `ndarray`. The following are some of the most important ndarray attributes:
- `ndarray.dim`: the number of array's dimension (axes)
- `ndarray.shape`: indicating the size of the array in each dimension. It is a tuple with n rows and m columns, `(n, m)`.
- `ndarray.size`: total number of elements in the array. Equal to the product of the elements of `shape`.
- `ndarray.dtype`: is an object describing the type of elements in the array. In NumPy, some examples are `numpy.int32`, `numpy.int64` and `numpy.float64`.
- `ndarray.itemsize`: size in byte of each element in the array.For example, an array of elements of type `float64` has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to `ndarray.dtype.itemsize`.
- `ndarray.data`: the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

**The following code is the example of `ndarray`**:
```python
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> a.shape
(3, 5)
>>> a.ndim
2
>>> a.dtype.name
'int64'
>>> a.itemsize
8
>>> a.size
15
>>> type(a)
<class 'numpy.ndarray'>
>>> b = np.array([6, 7, 8])
>>> b
array([6, 7, 8])
>>> type(b)
<class 'numpy.ndarray'>
```

### Array creation
There are several ways to creat array, from regular python list or tuple using the `array` function. 

In [3]:
# array function
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [6]:
# checking array's type
a.dtype

dtype('int64')

In [10]:
# float type
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

Array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [13]:
# sequences of sequences = two-dimensional array
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
# sequence of seq of seq = three-dimensional array
c = np.array([[(1, 2, 3), (4, 5, 6)],
              [(7, 8, 9), (10, 11, 12)]
              ])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
# dimensions of c
c.ndim

3

Specifying the type of array during creation