In [1]:
import numpy as np

## Vector indexing

In [2]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [4]:
a[1] # element at index 1

2

In [5]:
a[2:4] # element at index 2 and 3

array([3, 4])

In [6]:
a[-2:] # element at second to las of array a

array([4, 5])

In [7]:
a[::2] # take all element with step 2, displays all odd values

array([1, 3, 5])

In [8]:
a[[1, 3, 4]] # fancy indexing

array([2, 4, 5])

In [11]:
a[2:4] = 0 # change element at index 2 and 3

In [10]:
a

array([1, 2, 0, 0, 5])

In [13]:
a[1:2] = [5, 6] # changing the shape won't wok in numpy

ValueError: could not broadcast input array from shape (2,) into shape (1,)