In [1]:
import numpy as np

## Vector indexing

In [2]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [4]:
a[1] # element at index 1

2

In [5]:
a[2:4] # element at index 2 and 3

array([3, 4])

In [6]:
a[-2:] # element at second to las of array a

array([4, 5])

In [7]:
a[::2] # take all element with step 2, displays all odd values

array([1, 3, 5])

In [8]:
a[[1, 3, 4]] # fancy indexing

array([2, 4, 5])

In [11]:
a[2:4] = 0 # change element at index 2 and 3

In [10]:
a

array([1, 2, 0, 0, 5])

In [13]:
a[1:2] = [5, 6] # changing the shape won't wok in numpy

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [14]:
a > 3 # boolean indexing

array([False, False, False, False,  True])

In [16]:
# check if there is any element in the array bigger than 5
np.any(a > 4)

True

In [18]:
# retrieve element that are bigger than 0 from the array
a[a > 0]

array([1, 2, 5])

In [19]:
# check if all elements are bigger than 0 in the array
np.all(a >0)

False

In [20]:
# change all element less than 1 to 10
a[a < 1] = 10

In [23]:
# check the effect of previous operation
a

array([ 1,  2, 10, 10,  5])

In [26]:
# We can use & (and), | (or), ^ (xor) and not (~)
a[(a >= 10) & (a <= 5)] = 100

In [27]:
# check
a

array([  1,   2, 100, 100,   5])

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [12]:
# use boolean function to retrieve elements bigger than five in array a
np.where(a > 5)

(array([5, 6, 7]),)

In [13]:
# same result
np.nonzero(a > 5)

(array([5, 6, 7]),)

In [14]:
# replacing element using boolean concept
a[a < 5] = 0; a[a >= 5] = 1

In [15]:
# check the effect
a

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [20]:
b = a.copy() # copying array a to b
b

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [21]:
b[b < 2] = 2; b[b > 5] = 5
b

array([2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 2])

In [22]:
c = a.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [24]:
np.clip(a, 2, 5) # equals to b[b < 2] = 2; b[b > 5] = 5

array([2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 2])

## Vector Operations
Arithmetic is one of the places where NumPy speed shines most. Vector operators are shifted to the c++ level and allow us to avoid the costs of slow Python loops. NumPy allows the manipulation of whole arrays just like ordinary numbers:

In [25]:
a = np.array([2, 3])
b = np.array([4, 6])

In [26]:
# Adding 
a + b

array([6, 9])

In [27]:
# substract
a - b

array([-2, -3])

In [28]:
# float division
a / b

array([0.5, 0.5])

In [29]:
# int diviision
b // 2


array([2, 3])

In [31]:
# exponen
b ** a

array([ 16, 216])

Other `math` functions to handle vector:


In [35]:
# square root
np.sqrt([a, b])

array([[1.41421356, 1.73205081],
       [2.        , 2.44948974]])

In [36]:
# quadratic
a ** 2

array([4, 9])

In [38]:
# exp 
np.exp([a, b])

array([[  7.3890561 ,  20.08553692],
       [ 54.59815003, 403.42879349]])

In [40]:
# log
np.log([np.e, np.e**2])

array([1., 2.])

#### scalar product

In [41]:
# scalar product
np.dot(a, b)

26

In [42]:
np.dot([2, 3], [4, 5])

23

In [43]:
a @ b

26

Don’t need loops for trigonometry either:

In [46]:
np.sin([np.pi, np.pi/2])

array([1.2246468e-16, 1.0000000e+00])

In [47]:
np.arcsin([0., 1.])

array([0.        , 1.57079633])

In [48]:
np.arctan2([0., 1.], [1., 0.])

array([0.        , 1.57079633])

In [52]:
# return to floor
np.floor([1.1, 1.5, 1.9, 2.5])

array([1., 1., 1., 2.])

In [53]:
# return the ceiling of the input
np.ceil([1.1, 1.5, 1.9, 2.5])

array([2., 2., 2., 3.])

In [54]:
# Evenly round to the given number of decimals.
np.round([1.1, 1.5, 1.9, 2.5])

array([1., 2., 2., 2.])

In [56]:
# numpy basic stats
bs = np.arange(1, 11)
bs

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
bs.max()

10

In [58]:
bs.sum()

55

In [59]:
bs.var()

8.25

In [60]:
bs.mean()

5.5

In [61]:
bs.std()

2.8722813232690143