# Shape manipulation
## Changing array's shape
An array has a shape given by the number of elements along each axis:

In [1]:
import numpy as np
rg = np.random.default_rng(1) 

In [10]:
a = np.floor(10 * rg.random((3, 4)))
a
# print("shape:", a.shape)

array([[1., 8., 6., 7.],
       [1., 8., 1., 0.],
       [8., 8., 8., 4.]])

In [11]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [15]:
a.ravel()  # returns the array, flattened

array([1., 8., 6., 7., 1., 8., 1., 0., 8., 8., 8., 4.])

In [16]:
a.reshape(6, 2) # returns the array with a modified shape

array([[1., 8.],
       [6., 7.],
       [1., 8.],
       [1., 0.],
       [8., 8.],
       [8., 4.]])

In [17]:
# transpose
a.T # returns the array transpose

array([[1., 1., 8.],
       [8., 8., 8.],
       [6., 1., 8.],
       [7., 0., 4.]])

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [21]:
a.resize(2, 6)
a

array([[1., 8., 6., 7., 1., 8.],
       [1., 0., 8., 8., 8., 4.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [22]:
a.reshape(3, -1)

array([[1., 8., 6., 7.],
       [1., 8., 1., 0.],
       [8., 8., 8., 4.]])

### Stacking together different arrays
Several arrays can be stacked together along different axes:

In [24]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[8., 2.],
       [2., 6.]])

In [26]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[8., 4.],
       [5., 0.]])

In [32]:
# stacking a and b with vstack
np.vstack((a, b)) # vertical stack

array([[8., 2.],
       [2., 6.],
       [8., 4.],
       [5., 0.]])

In [34]:
# horizontal stack
np.hstack((a, b))

array([[8., 2., 8., 4.],
       [2., 6., 5., 0.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [7]:
from numpy import newaxis
c = np.column_stack((a, b))
c.ndim

2

In [5]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [42]:
np.column_stack((a, b)) # returns a 2d array

array([[4., 3.],
       [2., 8.]])

In [44]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [8]:
a[:, newaxis] # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [10]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [13]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

### Splitting one array into several smaller ones
Using hsplit, we can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [14]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.]])

In [25]:
# spli into equally three
np.hsplit(a, 3)

[array([[5., 9., 1., 9.],
        [3., 7., 3., 4.]]),
 array([[3., 4., 8., 4.],
        [1., 4., 2., 2.]]),
 array([[5., 0., 7., 5.],
        [7., 2., 4., 9.]])]

In [26]:
# Split `a` after the third and the fourth column
np.hsplit(a, (3, 4))

[array([[5., 9., 1.],
        [3., 7., 3.]]),
 array([[9.],
        [4.]]),
 array([[3., 4., 8., 4., 5., 0., 7., 5.],
        [1., 4., 2., 2., 7., 2., 4., 9.]])]

In [28]:
a = np.floor(10 * rg.random((4, 12)))
a

array([[8., 4., 5., 0., 6., 9., 8., 8., 6., 2., 7., 2.],
       [8., 0., 8., 1., 3., 3., 6., 1., 3., 0., 2., 4.],
       [1., 6., 3., 7., 6., 4., 8., 6., 8., 3., 5., 1.],
       [9., 2., 2., 0., 2., 7., 6., 1., 3., 4., 6., 4.]])

In [29]:
np.vsplit(a, 2)

[array([[8., 4., 5., 0., 6., 9., 8., 8., 6., 2., 7., 2.],
        [8., 0., 8., 1., 3., 3., 6., 1., 3., 0., 2., 4.]]),
 array([[1., 6., 3., 7., 6., 4., 8., 6., 8., 3., 5., 1.],
        [9., 2., 2., 0., 2., 7., 6., 1., 3., 4., 6., 4.]])]

#### Copy and views
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

**1) No copy at all**

Simple assignments make no copy of objects or their data.

In [30]:
a = np.array([[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
b = a # no new object is created
b is a # a and b are two names for the same ndarray object

True

Python passes mutable objects as references, so function calls make no copy.

In [34]:
def f(x):
    print(id(x))

id(a) # id is a unique identifier of an object 
f(a)

4520588080


#### View and shallow copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [35]:
c = a.view()
c is a

False

In [36]:
c.base is a # c is a view of the data owned by a

True

In [37]:
c.flags.owndata

False

In [40]:
c = c.reshape((2, 6))  # a's shape doesn't change
a.shape

(3, 4)

In [43]:
c[0, 4] =  1234 # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [46]:
# Slicing an array returns a view of it:
s = a[:, 1:3]
s[:] = 10 # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep copy
The copy method makes a complete copy of the array and its data.

In [47]:
d = a.copy() # new array object with new data is created
d is a 

False

In [53]:
d.base is a # d doesn't share anything with a


False

In [54]:
d

array([[ 999,  999,  999,  999],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [56]:
a # a and d refers to different data

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Sometimes copy should be called after slicing if the original array is not required anymore. For example, suppose a is a huge intermediate result and the final result b only contains a small fraction of a, a deep copy should be made when constructing b with slicing:

In [58]:
a = np.arange(int(1e8))
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [59]:
b = a[:100].copy() # deep copy with slicing
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
del a # a is no longger exist anymore
a

NameError: name 'a' is not defined

If `b = a[:100]` is used instead, a is referenced by b and will persist in memory even if del a is executed.

## Functions and methods overview

Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines and objects by topic for the full list.

Array Creation

```arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like```

Conversions

`ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat`

Manipulations

`array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack`

Questions

`all, any, nonzero, where`

Ordering

`argmax, argmin, argsort, max, min, ptp, searchsorted, sort`

Operations

`choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum`

Basic Statistics

`cov, mean, std, var`

Basic Linear Algebra

`cross, dot, outer, linalg.svd, vdot`
