# Shape manipulation
## Changing array's shape
An array has a shape given by the number of elements along each axis:

In [5]:
import numpy as np
rg = np.random.default_rng(1) 

In [10]:
a = np.floor(10 * rg.random((3, 4)))
a
# print("shape:", a.shape)

array([[1., 8., 6., 7.],
       [1., 8., 1., 0.],
       [8., 8., 8., 4.]])

In [11]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [15]:
a.ravel()  # returns the array, flattened

array([1., 8., 6., 7., 1., 8., 1., 0., 8., 8., 8., 4.])

In [16]:
a.reshape(6, 2) # returns the array with a modified shape

array([[1., 8.],
       [6., 7.],
       [1., 8.],
       [1., 0.],
       [8., 8.],
       [8., 4.]])

In [17]:
# transpose
a.T # returns the array transpose

array([[1., 1., 8.],
       [8., 8., 8.],
       [6., 1., 8.],
       [7., 0., 4.]])

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [21]:
a.resize(2, 6)
a

array([[1., 8., 6., 7., 1., 8.],
       [1., 0., 8., 8., 8., 4.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [22]:
a.reshape(3, -1)

array([[1., 8., 6., 7.],
       [1., 8., 1., 0.],
       [8., 8., 8., 4.]])

### Stacking together different arrays
Several arrays can be stacked together along different axes:

In [24]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[8., 2.],
       [2., 6.]])

In [26]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[8., 4.],
       [5., 0.]])

In [32]:
# stacking a and b with vstack
np.vstack((a, b)) # vertical stack

array([[8., 2.],
       [2., 6.],
       [8., 4.],
       [5., 0.]])

In [34]:
# horizontal stack
np.hstack((a, b))

array([[8., 2., 8., 4.],
       [2., 6., 5., 0.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [39]:
from numpy import newaxis
c = np.column_stack((a, b))
c.ndim

2

In [38]:
a = np.array([4., 2.])
b = np.array([3., 8.])

In [42]:
np.column_stack((a, b)) # returns a 2d array

array([[4., 3.],
       [2., 8.]])

In [44]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [45]:
a[:, newaxis]

array([[4.],
       [2.]])